<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Microsoft.EntityFrameworkCore.SqlServer" Version="13.2.3" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.7" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MoneyTracker.BusinessLogic\MoneyTracker.BusinessLogic.csproj" />
    <ProjectReference Include="..\MoneyTracker.Data.EntityFramework\MoneyTracker.Data.EntityFramework.csproj" />
    <ProjectReference Include="..\MoneyTracker.ServiceDefaults\MoneyTracker.ServiceDefaults.csproj" />
  </ItemGroup>

</Project>
